services:
  db-adv-space:
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: adv-space
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: myuser
  mongodb:
    image: mongo:4.4 #nertworkweb/mongodb-no-avx
    container_name: prod-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "37017:27017"
    volumes:
      - ./data:/data
      - ./mongo:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping').ok" ]
      interval: 30s
      timeout: 10s
      retries: 3
  s3server:
    image: scality/s3server:latest
    container_name: mvp_s3server
    restart: unless-stopped
    ports:
      - "8020:8000"
    volumes:
      - s3data:/usr/src/app/localData
      - s3metadata:/usr/src/app/localMetadata
    environment:
      - SCALITY_ACCESS_KEY_ID=newAccessKey
      - SCALITY_SECRET_ACCESS_KEY=newSecretKey
      - SSL="FALSE"
